services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: ./migration
        target: /docker-entrypoint-initdb.d/